name: Auto Commit

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run update script
        run: |
          echo "Auto update at $(date)" >> log.txt

      - name: Set up Git identity
        run: |
          git config --global user.name "marufalaslam"
          git config --global user.email "maruf14@cse.pstu.ac.bd"  # use your GitHub email

      - name: Commit and push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add .
          git commit -m "🤖 $(date)" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin HEAD
