name: Auto Commit

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes
  workflow_dispatch: # allows manual run from GitHub UI

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run update script
        run: |
          echo "Auto update at $(date)" >> log.txt

      - name: Set Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "🤖 $(date)" || echo "No changes to commit"
          git push
